In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from allensdk.brain_observatory.behavior.behavior_project_cache import VisualBehaviorNeuropixelsProjectCache

### Create cache

In [3]:
drive_dir = "/Volumes/Brain2024"
cache = VisualBehaviorNeuropixelsProjectCache.from_local_cache(cache_dir=drive_dir, use_static_cache=True)

In [4]:
cache.list_manifest_file_names() # Okay we just load the latest version

['visual-behavior-neuropixels_project_manifest_v0.5.0.json']

In [5]:
behavior_sessions = cache.get_behavior_session_table()

In [8]:
behavior_sessions = cache.get_behavior_session_table()
print(f"Total number of behavior sessions: {len(behavior_sessions)}")

print()
types = behavior_sessions.session_type.unique()
print("Unique types of sessions (Training/Recording):")
print()
for i, session_type in enumerate(types, start=1):
    print(f"{i}. {session_type}")

Total number of behavior sessions: 3424

Unique types of sessions (Training/Recording):

1. HABITUATION_5_images_G_handoff_ready_5uL_reward
2. TRAINING_1_gratings
3. TRAINING_2_gratings_flashed
4. TRAINING_5_images_G_epilogue
5. TRAINING_3_images_G_10uL_reward
6. TRAINING_4_images_G_training
7. TRAINING_0_gratings_autorewards_15min
8. HABITUATION_5_images_G_handoff_ready_3uL_reward
9. TRAINING_5_images_G_handoff_ready_5uL_reward
10. TRAINING_4_images_G_training_7uL_reward
11. TRAINING_2_gratings_flashed_10uL_reward
12. TRAINING_1_gratings_10uL_reward
13. TRAINING_0_gratings_autorewards_15min_0uL_reward
14. TRAINING_5_images_G_epilogue_5uL_reward
15. EPHYS_1_images_G_3uL_reward
16. TRAINING_5_images_G_handoff_lapsed_5uL_reward
17. EPHYS_1_images_H_3uL_reward
18. HABITUATION_5_images_H_handoff_ready_5uL_reward
19. HABITUATION_5_images_H_handoff_ready_3uL_reward
20. TRAINING_5_images_H_handoff_ready_5uL_reward
21. TRAINING_3_images_H_10uL_reward
22. TRAINING_4_images_H_training_7uL_reward
23. TRAINING_5_images_H_epilogue_5uL_reward
24. TRAINING_5_images_H_handoff_lapsed_5uL_reward
25. EPHYS_1_images_G_5uL_reward
26. EPHYS_1_images_H_5uL_reward

In [9]:
types = behavior_sessions.session_type.unique()
print("Unique types of EPHYS sessions:")
print()
ephys_types = [session_type for session_type in types if 'EPHYS' in session_type]

for i, session_type in enumerate(ephys_types, start=1):
    print(f"{i}. {session_type}")

Unique types of EPHYS sessions:

1. EPHYS_1_images_G_3uL_reward
2. EPHYS_1_images_H_3uL_reward
3. EPHYS_1_images_G_5uL_reward
4. EPHYS_1_images_H_5uL_reward

### Get access to behaviral data

In [10]:
# load example mice

mouse_id = 506940
print('Number of behaviral sessions for an example mouse:', len(behavior_sessions[behavior_sessions['mouse_id']== mouse_id]))

Number of behaviral sessions for an example mouse: 27

In [13]:
behavior_sessions_example_mouse = behavior_sessions[behavior_sessions['mouse_id']== mouse_id]

#### Get behavior trials directly from `cache.get_behavior_session()`

_Can get it from the ecephys_session:_

In [16]:
# ecephys_session_id
session_id = 1053941483 
session = cache.get_ecephys_session(session_id)
metadata = session.metadata
metadata

/opt/anaconda3/envs/swdb2024/lib/python3.9/site-packages/hdmf/utils.py:668: UserWarning: Ignoring cached namespace 'core' version 2.6.0-alpha because version 2.7.0 is already loaded.
  return func(args[0], **pargs)

{'equipment_name': 'NP.1',
 'sex': 'M',
 'age_in_days': 180,
 'stimulus_frame_rate': 60.0,
 'session_type': 'EPHYS_1_images_H_3uL_reward',
 'date_of_acquisition': datetime.datetime(2020, 10, 2, 0, 3, 58, tzinfo=tzutc()),
 'reporter_line': 'Ai32(RCL-ChR2(H134R)_EYFP)',
 'cre_line': 'Sst-IRES-Cre',
 'behavior_session_uuid': UUID('330937b4-ec9e-4bc4-8567-f74666f52596'),
 'driver_line': ['Sst-IRES-Cre'],
 'mouse_id': '527749',
 'project_code': 'Not Available',
 'full_genotype': 'Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt',
 'behavior_session_id': 1053960987,
 'ecephys_session_id': 1053941483}

In [38]:
trials = session.trials
trials.head()

,start_time,stop_time,initial_image_name,change_image_name,is_change,change_time_no_display_delay,go,catch,lick_times,response_time,reward_time,reward_volume,hit,false_alarm,miss,correct_reject,aborted,auto_rewarded,change_frame,trial_length
trials_id,,,,,,,,,,,,,,,,,,,,
0,25.20983,26.19343,im104_r,im104_r,False,NaN,False,False,"[25.72637, 25.87602]",NaN,NaN,0.0,False,False,False,False,True,False,-99,0.98360
1,26.71046,28.34528,im104_r,im104_r,False,NaN,False,False,[28.02817],NaN,NaN,0.0,False,False,False,False,True,False,-99,1.63482
2,28.96234,32.73245,im104_r,im104_r,False,NaN,False,False,[32.39844],NaN,NaN,0.0,False,False,False,False,True,False,-99,3.77011
3,33.46618,35.85175,im104_r,im104_r,False,NaN,False,False,[35.53463],NaN,NaN,0.0,False,False,False,False,True,False,-99,2.38557
4,36.46863,39.62138,im104_r,im104_r,False,NaN,False,False,"[39.15441, 39.28716]",NaN,NaN,0.0,False,False,False,False,True,False,-99,3.15275

In [41]:
trials.tail()

,start_time,stop_time,initial_image_name,change_image_name,is_change,change_time_no_display_delay,go,catch,lick_times,response_time,reward_time,reward_volume,hit,false_alarm,miss,correct_reject,aborted,auto_rewarded,change_frame,trial_length
trials_id,,,,,,,,,,,,,,,,,,,,
595,3611.49208,3618.76483,im083_r,im024_r,True,3614.49490,True,False,"[3614.97902, 3615.11108, 3615.22784, 3615.3446...",3614.97902,3614.97902,0.003,True,False,False,False,False,False,215234,7.27275
596,3618.99803,3619.59865,im024_r,im024_r,False,NaN,False,False,[3619.28223],NaN,NaN,0.000,False,False,False,False,True,False,-99,0.60062
597,3619.74882,3622.36770,im024_r,im024_r,False,NaN,False,False,"[3621.73408, 3621.83335, 3621.9336, 3622.06724...",NaN,NaN,0.000,False,False,False,False,True,False,-99,2.61888
598,3622.75138,3623.11829,im024_r,im024_r,False,NaN,False,False,"[3622.81796, 3623.23466]",NaN,NaN,0.000,False,False,False,False,True,False,-99,0.36691
599,3623.50198,3631.50933,im024_r,im024_r,False,3627.25499,False,True,[],NaN,NaN,0.000,False,False,False,True,False,False,215999,8.00735

_or frome the behavior_session directly:_

Can get ids from `behavior_sessions_table`-- which contains metadata for each behavior session. Some behavior sessions have Neuropixels data associated with them, while others took place during training in the behavior facility. The different training stages that mice progressed through are described by the session_type

In [22]:
behavior_session_id = metadata['behavior_session_id']

In [23]:
behavior_session = cache.get_behavior_session(behavior_session_id)

/opt/anaconda3/envs/swdb2024/lib/python3.9/site-packages/hdmf/utils.py:668: UserWarning: Ignoring cached namespace 'core' version 2.6.0-alpha because version 2.7.0 is already loaded.
  return func(args[0], **pargs)

In [63]:
behavior_session.list_data_attributes_and_methods()

['behavior_session_id',
 'eye_tracking',
 'eye_tracking_rig_geometry',
 'get_performance_metrics',
 'get_reward_rate',
 'get_rolling_performance_df',
 'licks',
 'metadata',
 'raw_running_speed',
 'rewards',
 'running_speed',
 'stimulus_presentations',
 'stimulus_templates',
 'stimulus_timestamps',
 'task_parameters',
 'trials']

In [43]:
behavior_session.trials.head()

,start_time,stop_time,initial_image_name,change_image_name,is_change,change_time_no_display_delay,go,catch,lick_times,response_time,reward_time,reward_volume,hit,false_alarm,miss,correct_reject,aborted,auto_rewarded,change_frame,trial_length
trials_id,,,,,,,,,,,,,,,,,,,,
0,25.20983,26.19343,im104_r,im104_r,False,NaN,False,False,"[25.72637, 25.87602]",NaN,NaN,0.0,False,False,False,False,True,False,-99,0.98360
1,26.71046,28.34528,im104_r,im104_r,False,NaN,False,False,[28.02817],NaN,NaN,0.0,False,False,False,False,True,False,-99,1.63482
2,28.96234,32.73245,im104_r,im104_r,False,NaN,False,False,[32.39844],NaN,NaN,0.0,False,False,False,False,True,False,-99,3.77011
3,33.46618,35.85175,im104_r,im104_r,False,NaN,False,False,[35.53463],NaN,NaN,0.0,False,False,False,False,True,False,-99,2.38557
4,36.46863,39.62138,im104_r,im104_r,False,NaN,False,False,"[39.15441, 39.28716]",NaN,NaN,0.0,False,False,False,False,True,False,-99,3.15275

In [46]:
trials.columns

Index(['start_time', 'stop_time', 'initial_image_name', 'change_image_name',
       'is_change', 'change_time_no_display_delay', 'go', 'catch',
       'lick_times', 'response_time', 'reward_time', 'reward_volume', 'hit',
       'false_alarm', 'miss', 'correct_reject', 'aborted', 'auto_rewarded',
       'change_frame', 'trial_length'],
      dtype='object')

It's the same thing!

In [54]:
num_licks = len(behavior_session.licks) 
print("Total number of licks (not lick bout):", num_licks)

Total number of licks (not lick bout): 2990

In [53]:
behavior_session.get_performance_metrics()

{'trial_count': 600,
 'go_trial_count': 295,
 'catch_trial_count': 44,
 'hit_trial_count': 139,
 'miss_trial_count': 156,
 'false_alarm_trial_count': 1,
 'correct_reject_trial_count': 43,
 'auto_reward_count': 3,
 'earned_reward_count': 139,
 'total_reward_count': 142,
 'total_reward_volume': 0.43199999999999994,
 'maximum_reward_rate': 5.033826263778787,
 'engaged_trial_count': 440,
 'mean_hit_rate': 0.47388024381123905,
 'mean_hit_rate_uncorrected': 0.4765842752763324,
 'mean_hit_rate_engaged': 0.535890015217069,
 'mean_false_alarm_rate': 0.06851317111891128,
 'mean_false_alarm_rate_uncorrected': 0.02273562288668029,
 'mean_false_alarm_rate_engaged': 0.06896672016964904,
 'mean_dprime': 1.4274968629298022,
 'mean_dprime_engaged': 1.6116689051369812,
 'max_dprime': 2.2015497100616526,
 'max_dprime_engaged': 2.2015497100616526}

In [52]:
len(behavior_session.get_reward_rate()) # how is this defined? (for every trail actually)

600

<span style="color:orange">__Notes__:</span> that `trails` do not contain information about the the stimulus content

<span style="color:orange">__Question__:</span> what exactly compose of a trial?

### Also useful, stimulus table

In [55]:
stim_table = behavior_session.stimulus_presentations

In [60]:
len(stim_table)
print("How many stimulus presentations in session?", len(stim_table))

How many stimulus presentations in session? 13405

In [59]:
stim_table.head()

,stimulus_block,image_name,duration,start_time,end_time,start_frame,end_frame,is_change,is_image_novel,omitted,...,spatial_frequency,color,rewarded,orientation,temporal_frequency,active,position_x,contrast,is_sham_change,stimulus_index
stimulus_presentations_id,,,,,,,,,,,,,,,,,,,,,
0,0,im104_r,0.250212,25.254420,25.504632,60,75,False,True,False,...,NaN,NaN,False,NaN,NaN,True,NaN,NaN,False,-99
1,0,im104_r,0.250212,26.005057,26.255269,105,120,False,True,False,...,NaN,NaN,False,NaN,NaN,True,NaN,NaN,False,-99
2,0,im104_r,0.250208,26.755685,27.005892,150,165,False,True,False,...,NaN,NaN,False,NaN,NaN,True,NaN,NaN,False,-99
3,0,im104_r,0.250207,27.506307,27.756515,195,210,False,True,False,...,NaN,NaN,False,NaN,NaN,True,NaN,NaN,False,-99
4,0,im104_r,0.250213,28.256929,28.507142,240,255,False,True,False,...,NaN,NaN,False,NaN,NaN,True,NaN,NaN,False,-99

### Visualize behavior trial data on raster plot

In [ ]:
raster_start_time = 407
raster_end_time = 427